### ISSUE TITLE
Deprecate as.term for as_term

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/term#19]

**Comment by krlmlr** [comment]
Not sure we need `as_term()`, because coercion is now handled via `vec_cast()`. Old `as.term.character()` should become `term.character(repair = TRUE)` .

**Comment by joethorley** [comment]
Trouble is we have conflict between as.term.integer() which gets dimensions and then calls term.integer() which uses dimensions to create term vector. We may need to create a new function or perhaps require that user pass dimensions as named list.

**Comment by krlmlr** [comment]
Coercion shouldn't be handled by `vec_cast()` at all. We could:

- [x] Add an `as_term()` generic
- [x] Move all methods for `as.term()` to `as_term()`
- [x] Add an `as_term.default()` that forwards to `as.term()`
- [x] Keep the `as.term()` generic for downstream packages, issue soft-deprecation warning

```r
as.term <- function(x, ...) {
  out <- UseMethod("as.term")
  deprecate_soft(...)
  out
}

as.term.default <- function(x, ..., from_as_term = FALSE) {
  as_term(x, ...)
}

as_term.default <- function(x, ...) {
  as.term(x, ..., from_as_term = TRUE)
}```
