### ISSUE TITLE
How to handle term_rcrd() objects incorporated into data.frames

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/term#48]
``` r
library(term)
data.frame(x = term("a"))
#>   x
#> 1 a
data.frame(y = term_rcrd("a")) 
#>   y.par y.dim
#> 1     a     1
```

<sup>Created on 2020-08-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
We can use `vec_proxy()`:

``` r
vctrs::vec_proxy(term::term_rcrd("a"))
#>   par dim
#> 1   a   1
```

<sup>Created on 2020-08-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by joethorley** [comment]
Great thanks
